# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: Personal Website of Atil Taylan Karakas
meta_description: "Practitioner and developer @reformo and @efabrika. Coding since '97 but I'm neither a ninja nor guru nor junkie."

aboutPage: true
title: Personal Website of Atil Taylan Karakas
author: Atil Taylan Karakas
email: taylan@efabrika.com
description: >- # this means to ignore newlines until "baseurl:"
  Practitioner and developer <a href="https://reformo.net" target="_blank">@reformo</a> and <a href="https://efabrika.com" target="_blank">@efabrika</a>. <br/>Coding since '97 but I'm neither a ninja nor guru nor junkie.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mkorkmaz.com" # the base hostname & protocol for your site, e.g. http://example.com

personal_links: 
  twitter: _mehmet_korkmaz
  github: mkorkmaz
  linkedin: mehmetkorkmaz
  instagram: hellomynameisblablabla


google_analytics: 'UA-1479299-19'

permalink: /:year/:month/:title

# Build settings
markdown: kramdown
theme: minima
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-font-awesome-sass
  - jekyll-sitemap
  - jekyll-archives

font-awesome:
  assets: true

defaults:
  -
    scope:
      path: "_pages" # empty string for all files
      type: pages
    values:
      layout: default
  -
    scope:
      path: "" # empty string for all files
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: drafts
    values:
      layout: post

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
